receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317

processors:

exporters:
  logging:
  logzio/logs-dup:
    account_token: xxxxxxxxxxx
    region: us
    headers:
      user-agent: "akamai-handson-29-01-25"


service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors: []
      exporters:
      - logging
