receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317

processors:

exporters:
  debug:
    verbosity: detailed  
  logzio/logs:
    account_token: xxxxxxxxxxxxxxxxxxx
    region: us
    headers:
      user-agent: "akamai-handson-29-01-25"


service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors: []
      exporters:
      - debug
      - logzio/logs
