receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:
  batch: {}

exporters:
  debug:
    verbosity: detailed  
  logzio/logs:
    account_token: xxxxxxxxxxxxxxx
    region: us
    headers:
      user-agent: "akamai-handson-29-01-25"
  logzio/traces:
    account_token: yyyyyyyyyyyyyyy
    region: us
    headers:
      user-agent: "akamai-handson-29-01-25"

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors: [batch]
      exporters:
      - debug
      - logzio/traces
    logs:
      receivers:
      - otlp
      processors: [batch]
      exporters:
      - debug
      - logzio/logs
